### ISSUE TITLE
ICD not correctly updated when changing kms_key reference

### ISSUE THREAD

**Issue by ifs-pauljegouic** [IBM-Cloud/terraform-provider-ibm#1111]
Hi there,

### Terraform Version
0.12
1.2.1

### Affected Resource(s)
Please list the resources as a list, for example:
- database
- kms_key

### Debug Output
```hcl
 ~ key_protect_key              = "crn:v1:bluemix:public:kms:eu-de:a/9e87f2cde0fe48ee9e056bdad79d285d:c4ba8c82-bbd3-4ce8-bdb9-564fb82d1ad1:key:14fdb9d9-cde8-4f36-9f03-7815638f80c3" -> (known after apply)
```

### Expected Behavior

database updated with new key_crn

### Actual Behavior
database keep the previous reference of the key_crn

**Comment by hkantare** [comment]
We can't update key_crn once the database is created..
<img width="1280" alt="Screen Shot 2020-02-24 at 11 08 28 AM" src="https://user-images.githubusercontent.com/24930306/75130834-4ce15200-56f6-11ea-8f39-81ffe6b7bca2.png">


We will fix it not show any diff when we update the key crn value since these values can be used only during create of instance
