### ISSUE TITLE
Resource name unicity || data resource take name as input

### ISSUE THREAD

**Issue by ifs-pauljegouic** [IBM-Cloud/terraform-provider-ibm#1112]
Hello,

I was wondering, since the resource name are not unique and most of the data resource in your provider take the "name" as input.

Is there any reason ?

**Comment by ifs-pauljegouic** [comment]
Forever alone

**Comment by hkantare** [comment]
Its the basic design of datasources in Terraform . Datasources are mainly used to fetch the information regarding an instance which is created outside Terraform. So it makes users easy to fetch resource information based on some name like attribute rather ID.
https://www.terraform.io/docs/configuration/data-sources.html

**Comment by ifs-pauljegouic** [comment]
Yes but my wondering is why IBM Cloud has no unicity regarding the resource name ?

I am sure you are applying the "basic design" of terraform. But it seems incompatible with IBM Cloud strategy (multiple resource with the same name ...)

**Comment by stevestrutt** [comment]
@hkantare I think the question here is because IBM Cloud allows multiple resources to have the same name, which is incompatible with a data source implementation that uses just the name to identify a resource. 

For example IBM Cloud allows multiple VPC's in an account to have the same name. I believe they have to be in different ResourceGroups. The VPC data source does not provide a mechanism for handling this.

**Comment by hkantare** [comment]
Can you provide us with list of high priority datasources which we will investigate to add additional fields like reosurce_group_id or any other parameters supported by API

**Comment by hkantare** [comment]
closing the issue due to inactivity...Please reopen if required
