### ISSUE TITLE
Creating RabbitMQ instance crash when instance is in provisioning state

### ISSUE THREAD

**Issue by Mallear** [IBM-Cloud/terraform-provider-ibm#1191]
Hi there,

### Terraform Version
Terraform v0.12.23
+ provider.ibm v1.2.4

### Affected Resource(s)
- ibm_database

### Terraform Configuration Files
```hcl
resource "ibm_database" "database" {
  name              = "mq-test"
  plan              = "standard"
  location          = var.region
  resource_group_id = var.rg_id"

  service = "messages-for-rabbitmq"
  version = "3.7"

  service_endpoints = "public-and-private"
  members_memory_allocation_mb = 3072
  members_disk_allocation_mb   = 3072

}
```

### Debug Output
```
ibm_database.database: Creating...
2020/03/17 15:31:43 [TRACE] <root>: eval: *terraform.EvalApply
2020/03/17 15:31:43 [DEBUG] ibm_database.database: applying the planned Create change
2020/03/17 15:31:43 [TRACE] GRPCProvider: ApplyResourceChange
2020-03-17T15:31:43.589+0100 [DEBUG] plugin.terraform-provider-ibm_v1.2.4: 2020/03/17 15:31:43 [DEBUG] setting computed for "groups" from ComputedKeys
2020-03-17T15:31:43.589+0100 [DEBUG] plugin.terraform-provider-ibm_v1.2.4: 2020/03/17 15:31:43 [DEBUG] setting computed for "connectionstrings" from ComputedKeys
2020/03/17 15:31:45 [TRACE] dag/walk: vertex "provider.ibm (close)" is waiting for "ibm_database.database"
2020/03/17 15:31:45 [TRACE] dag/walk: vertex "meta.count-boundary (EachMode fixup)" is waiting for "ibm_database.database"
2020/03/17 15:31:45 [TRACE] dag/walk: vertex "root" is waiting for "meta.count-boundary (EachMode fixup)"
2020-03-17T15:31:48.506+0100 [DEBUG] plugin.terraform-provider-ibm_v1.2.4: 2020/03/17 15:31:48 [DEBUG] Waiting for state to become: [active]
2020/03/17 15:31:50 [TRACE] dag/walk: vertex "root" is waiting for "meta.count-boundary (EachMode fixup)"
2020/03/17 15:31:50 [TRACE] dag/walk: vertex "provider.ibm (close)" is waiting for "ibm_database.database"
2020/03/17 15:31:50 [TRACE] dag/walk: vertex "meta.count-boundary (EachMode fixup)" is waiting for "ibm_database.database"
ibm_database.database: Still creating... [10s elapsed]
2020/03/17 15:31:55 [TRACE] dag/walk: vertex "provider.ibm (close)" is waiting for "ibm_database.database"
2020/03/17 15:31:55 [TRACE] dag/walk: vertex "meta.count-boundary (EachMode fixup)" is waiting for "ibm_database.database"
2020/03/17 15:31:55 [TRACE] dag/walk: vertex "root" is waiting for "meta.count-boundary (EachMode fixup)"
2020/03/17 15:31:58 [DEBUG] ibm_database.database: apply errored, but we're indicating that via the Error pointer rather than returning it: Error waiting for create database instance () to complete: unexpected state 'provisioning', wanted target 'active'. last error: %!s(<nil>)
2020/03/17 15:31:58 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2020/03/17 15:31:58 [TRACE] EvalMaybeTainted: ibm_database.database encountered an error during creation, so it is now marked as tainted
2020/03/17 15:31:58 [TRACE] <root>: eval: *terraform.EvalWriteState
2020/03/17 15:31:58 [TRACE] EvalWriteState: removing state object for ibm_database.database
2020/03/17 15:31:58 [TRACE] <root>: eval: *terraform.EvalApplyProvisioners
2020/03/17 15:31:58 [TRACE] EvalApplyProvisioners: ibm_database.database has no state, so skipping provisioners
2020/03/17 15:31:58 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2020/03/17 15:31:58 [TRACE] EvalMaybeTainted: ibm_database.database encountered an error during creation, so it is now marked as tainted
2020/03/17 15:31:58 [TRACE] <root>: eval: *terraform.EvalWriteState
2020/03/17 15:31:58 [TRACE] EvalWriteState: removing state object for ibm_database.database
2020/03/17 15:31:58 [TRACE] <root>: eval: *terraform.EvalIf
2020/03/17 15:31:58 [TRACE] <root>: eval: *terraform.EvalIf
2020/03/17 15:31:58 [TRACE] <root>: eval: *terraform.EvalWriteDiff
2020/03/17 15:31:58 [TRACE] <root>: eval: *terraform.EvalApplyPost
2020/03/17 15:31:58 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: Error waiting for create database instance () to complete: unexpected state 'provisioning', wanted target 'active'. last error: %!s(<nil>)
2020/03/17 15:31:58 [ERROR] <root>: eval: *terraform.EvalSequence, err: Error waiting for create database instance () to complete: unexpected state 'provisioning', wanted target 'active'. last error: %!s(<nil>)
2020/03/17 15:31:58 [TRACE] [walkApply] Exiting eval tree: ibm_database.database
2020/03/17 15:31:58 [TRACE] vertex "ibm_database.database": visit complete
2020/03/17 15:31:58 [TRACE] dag/walk: upstream of "provider.ibm (close)" errored, so skipping
2020/03/17 15:31:58 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2020/03/17 15:31:58 [TRACE] dag/walk: upstream of "root" errored, so skipping

Error: Error waiting for create database instance () to complete: unexpected state 'provisioning', wanted target 'active'. last error: %!s(<nil>)

  on main.tf line 25, in resource "ibm_database" "database":
  25: resource "ibm_database" "database" {


2020-03-17T15:31:58.905+0100 [DEBUG] plugin: plugin process exited: path=/Users/sibellas/.terraform.d/plugins/terraform-provider-ibm_v1.2.4 pid=94924
2020-03-17T15:31:58.905+0100 [DEBUG] plugin: plugin exited
```

### Expected Behavior
Terraform deployment end when RabbitMQ instance is up and running.

### Actual Behavior
Terraform deployment end with an error when RabbitMQ instance is in `provisioning` state.

### Steps to Reproduce
1. `terraform apply`

### References
May have the same root cause as #1190

**Comment by ifs-pauljegouic** [comment]
Please fix ICD and provide information. It is not acceptable that a Cloud Provider does not communicate on issues.

**Comment by ifs-pauljegouic** [comment]
We are in Frankfurt, and there is issue related to this in the console.

**Comment by hkantare** [comment]
So may be any intermittent issue....

**Comment by ifs-pauljegouic** [comment]
Intermittent, but since this morning (8h ago), the team is not able to provision ICD

**Comment by Mallear** [comment]
IBM may have issues to provision ICD, but during my tests Terraform fails and instances are well deployed.

**Comment by ifs-pauljegouic** [comment]
You are lucky ... Mine is deployed but stuck into "provisioning" state.

But the result is that our state remain inconsistent.

Is IBM monitoring or healthchecking their services in other location than Dallas ?

**Comment by Mallear** [comment]
IBM sure has a problems monitoring its service and sending alerts about issues. I don't know where it's the good place to complain.

But that's definitly a different issue than this ticket.

**Comment by hkantare** [comment]
Terraform is internally  makes REST API call...to provision the instance..once the instance is provisioned we wait until state moves tp provission...Here it is failing in reading status information
...May be in we can make changes in resource to store the ID information in state file immediately..
after we provision.

If subsequent call fails also due to intermittent issues we should be able to terraform refresh after soem time

**Comment by Mallear** [comment]
Ok I misunderstood the problem. I though terraform provider did not manage `provisioning` state as a valid state while waiting the instance to be ready.

**Comment by JoniSanchez** [comment]
Hi, This is happening as well in MongoDB, ElasticSearch and Redis, we have tried several provider version releases and TF 11 and TF 12 versions. The output of the errror as follows:
`ibm_database.elastic-test: Still creating... [10s elapsed]
2020/03/17 17:28:12 [TRACE] dag/walk: vertex "root" is waiting for "provider.ibm (close)"
2020/03/17 17:28:12 [TRACE] dag/walk: vertex "provider.ibm (close)" is waiting for "ibm_database.elastic-test"
2020/03/17 17:28:12 [TRACE] dag/walk: vertex "meta.count-boundary (EachMode fixup)" is waiting for "ibm_database.elastic-test"
2020/03/17 17:28:17 [TRACE] dag/walk: vertex "root" is waiting for "provider.ibm (close)"
2020/03/17 17:28:17 [TRACE] dag/walk: vertex "meta.count-boundary (EachMode fixup)" is waiting for "ibm_database.elastic-test"
2020/03/17 17:28:17 [TRACE] dag/walk: vertex "provider.ibm (close)" is waiting for "ibm_database.elastic-test"
2020/03/17 17:28:19 [DEBUG] ibm_database.elastic-test: apply errored, but we're indicating that via the Error pointer rather than returning it: Error waiting for create database instance () to complete: unexpected state 'provisioning', wanted target 'active'. last error: %!s(<nil>)
2020/03/17 17:28:19 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2020/03/17 17:28:19 [TRACE] EvalMaybeTainted: ibm_database.elastic-test encountered an error during creation, so it is now marked as tainted
2020/03/17 17:28:19 [TRACE] <root>: eval: *terraform.EvalWriteState
2020/03/17 17:28:19 [TRACE] EvalWriteState: removing state object for ibm_database.elastic-test
2020/03/17 17:28:19 [TRACE] <root>: eval: *terraform.EvalApplyProvisioners
2020/03/17 17:28:19 [TRACE] EvalApplyProvisioners: ibm_database.elastic-test has no state, so skipping provisioners
2020/03/17 17:28:19 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2020/03/17 17:28:19 [TRACE] EvalMaybeTainted: ibm_database.elastic-test encountered an error during creation, so it is now marked as tainted
2020/03/17 17:28:19 [TRACE] <root>: eval: *terraform.EvalWriteState
2020/03/17 17:28:19 [TRACE] EvalWriteState: removing state object for ibm_database.elastic-test
2020/03/17 17:28:19 [TRACE] <root>: eval: *terraform.EvalIf
2020/03/17 17:28:19 [TRACE] <root>: eval: *terraform.EvalIf
2020/03/17 17:28:19 [TRACE] <root>: eval: *terraform.EvalWriteDiff
2020/03/17 17:28:19 [TRACE] <root>: eval: *terraform.EvalApplyPost
2020/03/17 17:28:19 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: Error waiting for create database instance () to complete: unexpected state 'provisioning', wanted target 'active'. last error: %!s(<nil>)
2020/03/17 17:28:19 [ERROR] <root>: eval: *terraform.EvalSequence, err: Error waiting for create database instance () to complete: unexpected state 'provisioning', wanted target 'active'. last error: %!s(<nil>)
2020/03/17 17:28:19 [TRACE] [walkApply] Exiting eval tree: ibm_database.elastic-test
2020/03/17 17:28:19 [TRACE] vertex "ibm_database.elastic-test": visit complete
2020/03/17 17:28:19 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2020/03/17 17:28:19 [TRACE] dag/walk: upstream of "provider.ibm (close)" errored, so skipping
2020/03/17 17:28:19 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020/03/17 17:28:19 [TRACE] statemgr.Filesystem: not making a backup, because the new snapshot is identical to the old
2020/03/17 17:28:19 [TRACE] statemgr.Filesystem: no state changes since last snapshot
2020/03/17 17:28:19 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate

Warning: Interpolation-only expressions are deprecated

  on _ibm.tf line 2, in provider "ibm":
   2:   bluemix_api_key    = "${var.ibm_bmx_api_key}"

Terraform 0.11 and earlier required all non-constant expressions to be
2020/03/17 17:28:19 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.

(and 9 more similar warnings elsewhere)


Error: Error waiting for create database instance () to complete: unexpected state 'provisioning', wanted target 'active'. last error: %!s(<nil>)

  on main.tf line 1, in resource "ibm_database" "elastic-test":
   1: resource "ibm_database" "elastic-test" {

2020/03/17 17:28:19 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock

2020-03-17T17:28:19.015+0100 [DEBUG] plugin: plugin process exited: path=/usr/local/bin/terraform-provider-ibm pid=6130
2020-03-17T17:28:19.015+0100 [DEBUG] plugin: plugin exited
make: *** [terraform-apply] Error 1`

**Comment by hkantare** [comment]
We do see some incident opened in ibm cloud
```
INVESTIGATING: IBM Cloud Databases Provisioning and Consumption issues in us-south
Component: Databases
Location: Dallas
Start time: 17 Mar 2020 6:00 PM
End time: N/A
Update time: 17 Mar 2020 9:31 PM
Type: Incident
ID: INC2159460

SERVICES/COMPONENTS AFFECTED:
- Databases

IMPACT:
- Users may experience issues executing control plane operations against IBM Cloud Databases instances.  This includes provisioning, scaling, running backups, etc.
- Users may also experience issues connecting to their IBM Cloud Databases instances.  This includes intermittent timeouts and degraded performance when running database workloads.

IMPACTED SERVICES:
Databases for PostgreSQL
Databases for Redis
Databases for etcd
Databases for Elasticsearch
Databases for MongoDB
Messages for RabbitMQ

STATUS:
- 2020-03-17 13:41 UTC - INVESTIGATING - We are aware of the issue and are currently investigating. More information will be provided as it becomes available.
```

**Comment by ifs-pauljegouic** [comment]
That also affects Frankfurt ;)

**Comment by JoniSanchez** [comment]
Hi,
Our problem is any area of Europe. We are seeing in the provider code that the "provisioning" status does not currently exist, it has one called "In Progress", we are changing the code to launch a new PR, but we believe that the new "provisioning" status has been added by IBM and in the provider we do not contemplate it. Line 25
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/ibm/resource_ibm_database.go

**Comment by hkantare** [comment]
Yes ..we are checking the response from API team the status is in "provisioning" we are planning to consider that status also.
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/bf4bcd0cdfb52d7ce6230472bfc0bd239ff3fdec/ibm/resource_ibm_database.go#L1158
We will fix the problem and push to master branch..

**Comment by JoniSanchez** [comment]
PR to solved.
https://github.com/IBM-Cloud/terraform-provider-ibm/compare/master...JoniSanchez:patch-1
