### ISSUE TITLE
ibm_database is created and added to terraform state even if apply is finished with error

### ISSUE THREAD

**Issue by serg-lavr** [IBM-Cloud/terraform-provider-ibm#1264]
When provider region is not equal to icm_database region `terraform apply` is failing with error, but ibm_database instance is still deployed. 

### Terraform Version
```
v0.11.13
provider.ibm v0.24.6
```
### Affected Resource(s)
- ibm_database

### Terraform Configuration Files
Example config:
```
provider "ibm" {
  region = "us-south"
}

resource "ibm_database" "test-database" {
  name                         = "test-postgres"
  location                     = "us-east"
  service                      = "databases-for-postgresql"
  plan                         = "standard"
  version                      = "12"
}
```
### Expected Behavior
Database is not created and is not added to state due to error.
### Actual Behavior
Database is created and added to terraform state.
### Steps to Reproduce
Run `terraform apply` on example config.

**Comment by hkantare** [comment]
Yes its working according to the desgin..Because we depends on two API one for resource_controller and another database API (region specific). 
For creating instance it uses global resource_controller API to create an instance where it doesn't depends up on region...so that why database is created and added to state.

For configuring additional properties it needs to call region specific endpoint..so it fails if its n't valid region

**Comment by serg-lavr** [comment]
@hkantare Thank you for response. Could you specify which additional properties are configured? Should database instance be redeployed to be configured properly?

**Comment by hkantare** [comment]
No we don't need to redeploy just next terraform comamnds should detect the changes and configure the properties
