### ISSUE TITLE
Support entitlement for ROKS IKS clusters

### ISSUE THREAD

**Issue by hkantare** [IBM-Cloud/terraform-provider-ibm#1350]
USAGE:
        ibmcloud ks cluster create classic ...
PARAMETERS:
...
--entitlement value          Optional: Set this flag to 'cloud_pak' only if you use this cluster with a Cloud Pak that has an OpenShift entitlement.

**Comment by indirakalagara** [comment]
Hi Team, 

Looks like we have a major problem using the following terraform script to create the Managed OCP cluster due to missing of the entitlement option. 
https://cloud.ibm.com/docs/terraform?topic=terraform-container-resources#classic-red-hat-openshift-on-ibm-cloud-cluster

The script is being executed successfully and creating the cluster.  However the OCP license cost is incurred against the worker nodes.   If we look at the IBM Cloud UI, based on the IBM ID, the entitlement option is presented with 2 values - a) Purchase additional licenses for this worker pool b) Apply my Cloud Pak OCP entitlement to this worker pool.   And when we chose the Cloud Pak OCP entitlement , OCP license cost is NOT incurred.   

But through the given terraform script , by default it is going with Purchase licenses option - which  incurs additional cost, although the user is entitled to use Cloud Pak OCP license. 
This is becoming a bottleneck  to proceed with the script and one of the major challenge currently facing by one of our IBM GSI.

Can you please take a look into the script and this feature , and provide the update at the earliest.

**Comment by hkantare** [comment]
Added support for entitlement as part of latest release
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.5.2
Doc will be updated soon
