### ISSUE TITLE
In VPC cluster, add the ability to retrieve the Load Balancer that was created for the cluster

### ISSUE THREAD

**Issue by l2fprod** [IBM-Cloud/terraform-provider-ibm#1606]
```sh
$ terraform -v
Terraform v0.12.26
+ provider.ibm v1.7.1
```

I have a VPC IKS Cluster in Gen 2

```hcl
resource "ibm_container_vpc_cluster" "cluster" {
  count = var.has_iks ? 1 : 0

  name              = "${var.name}-cluster"
  vpc_id            = ibm_is_vpc.vpc.id
  flavor            = var.iks_machine_type
  worker_count      = var.iks_worker_count
  resource_group_id = var.resource_group_id
  kube_version      = var.iks_version

  zones {
    subnet_id = ibm_is_subnet.subnet[0].id
    name      = "${var.region}-1"
  }
  zones {
    subnet_id = ibm_is_subnet.subnet[1].id
    name      = "${var.region}-2"
  }
  zones {
    subnet_id = ibm_is_subnet.subnet[2].id
    name      = "${var.region}-3"
  }

  tags = concat(var.tags, [ "vpc" ])
}
```

The IKS cluster is correctly created.

A Load Balancer is also created as a side-effect of creating the cluster. This Load Balancer is visible in my account:

![image](https://user-images.githubusercontent.com/12746550/86023595-7fc38b80-b9f1-11ea-8108-1dda1e4831ec.png)

How can I retrieve this Load Balancer so that I can:
- change its name to something a bit more meaningful
- tag the Load Balancer like all other resources in my account

**Comment by kroc353** [comment]
I created a similar issue , requesting ability to control the names of the VPC Load balancer and the VPC Virtual private endpoint gateway that are created automatically as part of the cluster creation:
https://github.com/IBM-Cloud/terraform-provider-ibm/issues/2776

I did subsequently read in the documentation that we're not requested to change the name of these resources.  

If this helps you in the interim while they provide a feature enhancement @l2fprod .  Here is the data lookups I use to get the load balancer , so that I can attach security groups to it.
```
data "ibm_is_lbs" "lbs" {
  depends_on = [
    ibm_container_vpc_cluster.cluster
  ]
}

data "ibm_is_lb" "lb" {
  depends_on = [
    ibm_container_vpc_cluster.cluster,
    data.ibm_is_lbs.lbs
  ]
  name = [for x in data.ibm_is_lbs.lbs.load_balancers : x["name"] if split("-", x.name)[1] == ibm_container_vpc_cluster.cluster.id][0]
}
```

**Comment by kavya498** [comment]
Closing this issue,
Kindly track using #2776.
Thanks.
