### ISSUE TITLE
Provide version information in provider release

### ISSUE THREAD

**Issue by ruben-burr** [IBM-Cloud/terraform-provider-ibm#183]
Hi there,

as we want to follow the recommendation for using version constraints for terraform providers, we currently have to rename the extracted provider file to contain the version information. Could you please include this in the release creation process? The zipped file of the current version should then be named terraform-provider-ibm_v0.8.0

Thanks, Ruben

**Comment by kugelr** [comment]
+1

This is also desired naming scheme proposed by HashiCorp. Would be happy to see this implemented.

_"The naming scheme for provider plugins is terraform-provider-NAME_vX.Y.Z, and Terraform uses the name to understand the name and version of a particular provider binary. Third-party plugins will often be distributed with an appropriate filename already set in the distribution archive so that it can be extracted directly into the plugin directory described above."
https://www.terraform.io/docs/configuration/providers.html (section Third-party plugins)
