### ISSUE TITLE
Inclusion of force-delete=true with COS_bucket

### ISSUE THREAD

**Issue by VidyasagarMSC** [IBM-Cloud/terraform-provider-ibm#2017]
Hi there,

It would be good to have an option to force-delete a non-empty COS bucket. S3 has an option 

```
force-delete=true
```
to forcible delete a non-empty COS bucket

**Comment by data-henrik** [comment]
related to #1827

**Comment by hkantare** [comment]
Fixed in latest release
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.17.0

**Comment by hkantare** [comment]
closing the issue

**Comment by kjoconnor** [comment]
@hkantare I'm seeing `force_delete` being added to my buckets that have already been created and are only getting changes to `archive_rule` or something easily modifiable like that. They are being marked as "in-place" modifications and not delete and recreates.

Do I need to manually set `force_delete` on all of my Terraform managed COS buckets now? What happens if `force_delete` is applied?

**Comment by hkantare** [comment]
force_delete is a parameter just used only during destroy.If user set this parameter it destroyed the buckets even if we have some objects attached to it
