### ISSUE TITLE
Add support for enabling platform metrics on Container Registry

### ISSUE THREAD

**Issue by dprosper** [IBM-Cloud/terraform-provider-ibm#2186]
Currently there is no resource available in the provider to enable platform metrics for the Container Registry as described in here: https://cloud.ibm.com/docs/Registry?topic=Registry-registry_monitor_sysdig#registry_enable_platform_metrics

Can a resource be added to enable/disable this capability?

**Comment by hkantare** [comment]
@jhart1685 Can you please look into this request

**Comment by jhart1685** [comment]
@dprosper - Could you please submit this request as an idea: https://ibmcloud.ideas.ibm.com 

The focus for the Container Registry Terraform artifacts has been around namespaces, and retention settings (which are governed at the namespace level). So far we have not exposed account-level settings through Terraform.

Raising the idea will get visibility to our product management team, so that they can evaluate and prioritise alongside other requirements.

**Comment by dprosper** [comment]
@jhart1685  Thank you, submitted: IDEA-I-3421

**Comment by jhart1685** [comment]
Thanks @dprosper 

@hkantare - I guess you'd typically now close this issue, as the feature request has been raised? I'll leave that to you.. (am not able to do it myself anyway).

**Comment by hkantare** [comment]
closing the issue based on above comments
