### ISSUE TITLE
Add support to enable or disable LB as part of kubernetes cluster creation in VPC

### ISSUE THREAD

**Issue by kd2dhamecha** [IBM-Cloud/terraform-provider-ibm#2675]
hi team ,

As such,  there is no param or flag available to enable or disable load balancer as part of  ibm_container_vpc_cluster resource.
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/container_vpc_cluster#argument-reference

And to disable the load balancer on created cluster, we need use extra data source ibm_container_vpc_cluster to fetch cluster id's and passed it to ibm_container_vpc_alb resource to disable the it , which increase the provision time.

Can you please add support to enable/disable LB in ibm_container_vpc_cluster resource ?

Thanks.

**Comment by ctrath** [comment]
Hi.. We currently don't support this in IBM Cloud Kubernetes Service cluster creation, so it's really not possible to model this feature in our Terraform provider since it can't currently be done in the infrastructure.  We will take this idea into account when me make future improvements to IBM Cloud Kubernetes Service provisioning.

**Comment by hkantare** [comment]
closing on the above comments
