### ISSUE TITLE
Clarification of arguments to ibm_pi_instance

### ISSUE THREAD

**Issue by r-venables** [IBM-Cloud/terraform-provider-ibm#3499]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s) or Datasource(s)

* ibm_pi_instance

### Description

The ibm_pi_instance documentation states that the network ID should be specified in the pi_network object. This should be amended to say it requires the pi_network_name:

```
pi_network {
  network_id = ibm_pi_network.build_network.pi_network_name
  ip_address = var.build_ip
}
```

The ibm_pi_instance documentation states that pi_volume_ids is a list of volume IDs. This should be amended to say that it requires a list of volume_id:

```
 pi_volume_ids = [for v in ibm_pi_volume.volume_list : v.volume_id]
```

**Comment by ChaseRun** [comment]
I looked at the IBM Terraform documentation and the IBM Power API documentation for IBM Power Instances.
 - `pi_network`
   - The `pi_network` represents a list of networks. The only required value when assigning an individual network, is `network_id`. The `network_id` corresponds to the `ibm_pi_network` -> `id`.
   - The documentation explains this: The `pi_network` block supports `network_id` and `ip_address`. I will update the documentation to explain that `network_id` is required.
   - I'm not sure where you are seeing that `pi_network_name` would be required
 - `pi_volume_ids`
   -   Since `pi_volume_ids` in an optional argument, I don't think it makes sense to change to documentation wording to use the word "requires"

**Comment by jwcroppe** [comment]
@r-venables, thanks for the report... can you highlight which page you found with those references?

**Comment by r-venables** [comment]
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/pi_instance

**Comment by jwcroppe** [comment]
Thanks... @ChaseRun - please see above.

**Comment by yussufsh** [comment]
- pi_network:
  - The pi_network block should take network ID. Also see the API where there is no mention of network name to be specified https://cloud.ibm.com/apidocs/power-cloud#pcloud-pvminstances-post. The fact that name also work is a plus here but we recommend using the network ID instead of name.

- pi_volume_ids:
  - `list of volume IDs` is just descriptive representation of `list of volume_id`. It could be `volume_id` if you are using the resource attribute OR just `id` if you are using a data source. So I do not think we should change it.

**Comment by ChaseRun** [comment]
For now I am going to close this issue. Currently we are planning to review/update all attributes and arguments for each power resource and data source. If an attribute is available from the power api, and if it isn't currently accessible with terraform, we plan on adding it.
