### ISSUE TITLE
Incorrect values returns for volume_status and pi_memory in just provisioned machine in Attention/Warning state.

### ISSUE THREAD

**Issue by Kuldip-Nanda** [IBM-Cloud/terraform-provider-ibm#3582]
These issues were found during the development of the manageiq manageiq-providers-ibm_cloud plugin test framework using Terraform provider
```
Terraform v1.1.4
on linux_amd64

provider registry.terraform.io/hashicorp/random v2.3.1
provider registry.terraform.io/ibm-cloud/ibm v1.38.0
```

This test provision's a simple AIX installed PowerVS VSI attached to two subnets, and a data volume using terraform script. While developing this it was found the state of the machine on IBM WebConsole going to ATTENTION state.
When the machine is in WARNING or ATTENTION state, Terraform returns incorrect state information.

The volume_status attribute shows as Available, rather than In-use.

The pi_memory shows 0 bytes rather than the correct value.

These values are also different from those returned by the WEB API. When the VM state changes to green, terraform script returns correct values for memory and volume used.

**Comment by yussufsh** [comment]
The Terraform reads the GET API which will have actual values when the VM is at target state. As you are looking at in between state, it is not guaranteed that the VM attributes will be correct. We have no control to read proper values from the backend if VM is not healthy.

VM health status attribute was introduced only for specific purpose (core OS) where user is asking Terraform to exit before the target health state of `OK`.

**Comment by Kuldip-Nanda** [comment]
Yussuf, although I understand the implementation as an engineer, but as a user, I do not know the correct value nor I have anyway to go to the Healthy State. How do I recover. This is a dead end for me as a user.

Is it possible, to have  a set of API's be provided which return the correct value for Healthy state only. Otherwise provide message which states the VM attributes are not guaranteed to be correct. At least I am guaranteed correct values.

**Comment by yussufsh** [comment]
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/pi_instance#pi_health_status mentions the allowed values to be specified for instance health status to poll. If you change the default value and exit Terraform before you can say the instance deployment is SUCCESS, you are not guaranteed of proper values for all attributes.
As you had mentioned when VM state is green you can read the values, so run `terraform refresh` or `terraform apply` again so that the instance attributes are fetched completely.

When you change a variable from the default provided you are expected to know how it works as an end user.

I am going to close this issue as the resource is working as expected. Feel free to reopen in case it is still a blocker for you.

**Comment by Kuldip-Nanda** [comment]
Thanks. Let me check again.
