### ISSUE TITLE
ibm_pi_cloud_connection_attach

### ISSUE THREAD

**Issue by surajbharadwaj** [IBM-Cloud/terraform-provider-ibm#3641]
I would like to have a workflow with 2 modules:
**cloud_connection_create
cloud_connection_attach**
In first module i am just creating the cloud connection without attaching pvs subnets or vpcs.
in second module i want to attach pvs subnets and VPCs to the existing resources.

This also makes sense, when a customer has existing cloud connections and just wants to attach(update) the pvs subnets and vpc to cloud connection, Then this facilitates 2 scenarios: 
1. No cloud connection--->**Create new** cloud connection using **ibm_pi_cloud_connection** and then attach pvs subnets and vpcs using **ibm_pi_cloud_connection_attach**
2. Reuse existing cloud connection by just attaching pvs subnets and vpcs using just  **ibm_pi_cloud_connection_attach**

https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/pi_cloud_connection

**Comment by yussufsh** [comment]
As discussed with you...
`we cannot provide ibm_pi_cloud_connection_update that way all resources may need a update resource so that you can say I want to update an instance in module 2 which is created in module 1`

We can only introduce network attach resource. That is a valid request since it is a different flow and I am working on it. It will take the cloud connection id and the network id to attach to the cloud connection with no computed values.

We cannot use new resource to update VPC since it is edit of the existing resource `ibm_pi_cloud_connection`. You can update the VPC CRN in the same resource and run apply again.

**Comment by surajbharadwaj** [comment]
Okay that works :) Will wait for ibm_pi_cloud_connection_attach. Can you please put this enhancement request at a higher priority if possible  ?

**Comment by yussufsh** [comment]
I should be able to raise the PR in next couple of days depending on other support requests.
