### ISSUE TITLE
Add Resource Group support for VSI and Bare Metal

### ISSUE THREAD

**Issue by kskewes** [IBM-Cloud/terraform-provider-ibm#400]
### Terraform Version
```
$ terraform -v
Terraform v0.11.8
```

### Affected Resource(s)

- ibm_compute_instance
- ibm_compute_bare_metal

### Terraform Configuration Files
N/A, per examples in docs.

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
I should be able to provision virtual machines and bare metal into a resource_group.

### Actual Behavior

```
* ibm_compute_bare_metal.instance: Encountered problem trying to get the bare metal order template: SoftLayer_Exception_Public: Access Denied.  (HTTP 401)
```

### Steps to Reproduce

(Provision into Resource Group)
1. Create a Resource Group
2. Try following: https://ibm-cloud.github.io/tf-ibm-docs/v0.12.0/r/compute_vm_instance.html
3. Try following: https://ibm-cloud.github.io/tf-ibm-docs/v0.12.0/d/compute_bare_metal.html
4. Will fail due to no ability to specify resource_group (unlike clusters).

### Important Factoids
N/A

**Comment by kskewes** [comment]
Resource groups are not supported in soft layer which is where vsi and bare metal (and networking, storage, etc) resources are.

**Comment by stevestrutt** [comment]
Resource groups (and IAM) will be supported on Gen2 infrastructure with the new RIAAS infrastructure API. Until then infrastructure provisioning depends on the security rights granted to the SL user/SL API key used by Terraform. There is a plan to merge to a single API for IBM Cloud instead of BMX and SL. I have no knowledge of the difference it will make to the security rights Terraform needs.

**Comment by hkantare** [comment]
closing the issue..
