### ISSUE TITLE
Private and Public VLAN ID's should not be required

### ISSUE THREAD

**Issue by kskewes** [IBM-Cloud/terraform-provider-ibm#401]
### Terraform Version
```
$ terraform -v
Terraform v0.11.8
```

### Affected Resource(s)

- Kubernetes clusters

### Terraform Configuration Files
N/A, per examples in docs.

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
I should be able to provision additional zones in a cluster without specifying the VLAN ID per: 

https://console.bluemix.net/docs/containers/cs_cli_reference.html#worker-pool
```
--private-vlan PRIVATE_VLAN
The ID of the private VLAN. This value is conditional.
<snip>
If you do not have a private or public VLAN in that zone, do not specify this option. A private and a public VLAN are automatically created for you when you initially add a new zone to your worker pool.
```

### Actual Behavior

Terraform complains that the PRIVATE_VLAN_ID is required.

### Steps to Reproduce

Follow the example multi-zone cluster guide in the docs.

### Important Factoids
N/A

**Comment by Praveengostu** [comment]
@kskewes you scenario is to add more zones to the worker pool of a cluster?

**Comment by kskewes** [comment]
Yes. This was when I had vlan in cluster default zone but had no vlan in second zone I was adding.
I had to use IBM cloud cli to provision cluster.

**Comment by Praveengostu** [comment]
Hi @kskewes We had made the private vlan optional for resource `ibm_container_worker_pool_zone_attachment`. But these are conditional. If you do not have a private or public VLAN in the zone, these are optional. A private and a public VLAN are automatically created for you when you initially add a new zone to your worker pool.  If you already have a private/public vlan in the zone then these are required and to be passed by user. 
The fix is available in public branch now and will be available part of next release.

**Comment by kskewes** [comment]
Thanks very much!
