### ISSUE TITLE
[ibm_sm_iam_credentials_secret] TTL field only accepts integers

### ISSUE THREAD

**Issue by alex-reiff** [IBM-Cloud/terraform-provider-ibm#4464]
The TTL field expects an integer, so values like `960h` or `60m` do not work like they should.

```
│ Error: expected ttl to represent an integer
│
│   with module.dynamic_serviceid_apikey1.ibm_sm_iam_credentials_secret.sm_iam_credentials_secret,
│   on ../../main.tf line 25, in resource "ibm_sm_iam_credentials_secret" "sm_iam_credentials_secret":
│   25:   ttl             = var.sm_iam_secret_ttl
│
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

```
Terraform v1.4.4
on darwin_amd64
+ provider registry.terraform.io/ibm-cloud/ibm v1.51.0
```

### Affected Resource(s)

* ibm_sm_iam_credentials_secret

### Terraform Configuration Files

(internal link) https://github.ibm.com/GoldenEye/iam-serviceid-apikey-secrets-manager-module/tree/master/examples/complete-no-rotation-policy

### Steps to Reproduce

1. `TF_VAR_sm_iam_secret_ttl=960h`
2. `terraform apply`

### References

* #0000

**Comment by haimsch** [comment]
The `ttl` field accepts only integer values (number of seconds). See the documentation of the ttl field here https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/sm_iam_credentials_secret
The example in this page is still `ttl = "30m"` but this has been fixed in PR #4530
Note that the Secrets Manager API does support a value like "30m" for ttl, but in the Terraform provider we had to limit the possible values to integers only (because in the the response it is always integer).
