### ISSUE TITLE
Feature Request: add credentials to machines 

### ISSUE THREAD

**Issue by ThomasUllrich666** [IBM-Cloud/terraform-provider-ibm#506]
Hi there,
can you provide an opportunity to add credentials to devices? Right now there is no way to add you own credentials to a device (e.g. User: root ; Password: myOwnPassword). The Operating System credentials for Linux (root) and Windows (Administrator) are set automatically by Softlayer.

**Comment by stevestrutt** [comment]
SoftLayer already support initial configuration of a VSI image at boot time using "user_metadata" and this is supported on the VSI resource. A script can be used to configure literally anything, including new users and passwords. In Terraform the easiest by to use this is via a CloudInit template. Largely unannounced SoftLayer introduced CloudInit support in many of the VSI images.     https://console.bluemix.net/docs/infrastructure/image-templates/image_cloud-init.html#provisioning-with-a-cloud-init-enabled-image I created an example in the provider repo that demonstates how to use cloudinit https://github.com/IBM-Cloud/terraform-provider-ibm/tree/master/examples/ibm-vsi-cloudinit

**Comment by ThomasUllrich666** [comment]
@stevestrutt: Thanks for your reply. Ok there are many ways to add a User with help of Terraform or CloudInit. But why are we not using the Softlayer API for this kind of things? I don't want to learn CloudInit if I have an option to use it as a Terraform method.

**Comment by stevestrutt** [comment]
@ThomasUllrich666 sorry I don't follow your line of thinking. The IBM provider does support the Softlayer API to do this. Via the Terraform provider you can specify additional SL VSI configuration parameters, scripts, URLs etc, via the `user_metadata` field. This is exactly the same as you can do today with the Cloud UI of using any of the SL API bindings via scripts. No different.  Terraform is not adding or taking away function. 

I think the underlying issue is that SL does a poor job of documenting how you do this today via the UI or API. It is left to the user to create their own scripts to configure users etc. Terraform adds and takes away nothing. The positive is that Terraform makes it easier as it provides a CloudInit template.

Terraform explictly does not attempt to work at the software/application level. Userids are at the application level and this is typically left to a CM tool like Chef, Puppet or Ansible.

**Comment by ThomasUllrich666** [comment]
@stevestrutt thank you for clarification. I understand your way of thinking better now. I close this ticket
