### ISSUE TITLE
PowerVS: ibm_pi_instance: pi_replicants parameter , on destroy fails to clean up., on reapply config changes

### ISSUE THREAD

**Issue by surajsbharadwaj** [IBM-Cloud/terraform-provider-ibm#5168]
There is a major bug with **ibm_pi_instance**. resource,
When using **pi_replicants** as parameter:
For example if i pass in value 3 
On destroy it doesnt destroy the second and third instance. Only the first instance is destroyed.

**Comment by surajsbharadwaj** [comment]
On reapply again , to make sure there is no infrastructure changes,
it tries to **rename** the instance and also removes the **placement_group_id** which it created automatically when using **pi_replicants**
```
//  # module.powervs_instance_primary.module.pi_instance.ibm_pi_instance.instance will be updated in-place
  ~ resource "ibm_pi_instance" "instance" {
        id                             = "848b2d38-6264-460b-a09d-7095fb3b3f2e/870053af-38a1-4acf-baa4-507a028a31ec"
      ~ pi_instance_name               = "replica-2-1" -> "replica-2"
      - pi_placement_group_id          = "fb9b38bc-0bbd-4ace-b540-c077399fd39d" -> null
        # (32 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }

Plan: 1 to add, 1 to change, 0 to destroy.
```

**Comment by hkantare** [comment]
Shared the issue with power team
[@ismirlia](https://ibm-cloudplatform.slack.com/team/W8FNY9DMZ)

**Comment by ismirlia** [comment]
@surajsbharadwaj can you please share the configuration you are doing?

**Comment by ismirlia** [comment]
I opened: https://github.com/IBM-Cloud/terraform-provider-ibm/pull/5176 to fix the issue.

**Comment by surajsbharadwaj** [comment]
Does it also handle the reapply part ?

**Comment by ismirlia** [comment]
@surajsbharadwaj Let me double on that.

**Comment by surajsbharadwaj** [comment]
Can you support the reapply without any modifications? This is important. This will be included in our automation and published to catalog tile

**Comment by surajsbharadwaj** [comment]
Else change the way data is inserted in the state file. Make a dictionary with the instance name as key and values as list of instances..

**Comment by ismirlia** [comment]
> Else change the way data is inserted in the state file. Make a dictionary with the instance name as key and values as list of instances..

@surajsbharadwaj you are gonna have to give me an example of how that would work in the terraform code because I don't know how to make that work perfectly.

In this particular resource we require a name to be passed in say, "test." For the replicant property to be used, we require replicant affinity, number of replicants, and prefix or suffix to be set. When instances are created it sets their name to be prefix+name or name+suffix. So for like replicant of 3 and suffix set we create instances with the following name.

test-1, test-2, and test-3

but the configuration passed in didn't change (we still have "test" as the name argument).

If we apply again after creation in this situation, we see that the name in the configuration (test) and name read (test-1) don't match and it tries to update the name.
