### ISSUE TITLE
New CIS WAF automated activation

### ISSUE THREAD

**Issue by pauljegouic** [IBM-Cloud/terraform-provider-ibm#5494]
Hello there,

We are facing an issue with the new way of activating the WAF at Cloudflare Internet Service level.

Before we used to use the : `ibm_cis_domain_settings` but it looks like that new domains now need to activate WAF through : `ibm_cis_rulesets`

My issue is that this resource cannot be created through Terraform, but needs an import which is not satisfiable with our automation process.

As there is no option to create a ruleset resource, it is required to use import module to generate the respective resource configurations  and use the import command to populate the state file, as stated at the end of this page.

As far as I understand, ruleset ID is created with the domain, therefore, we should be able to activate WAF ruleset on our domain ruleset.

From my user prospective this "evolution" is actually a regression from the Terraform automation prospective.

**Comment by arjunchauhanibm** [comment]
Hi @pauljegouic, 

For now we only support the phase `http_request_firewall_managed` therefore we can not create custom rulesets. 
If we want to deploy managed rulesets that can be done by using the entrypoint ruleset resource. 

Can you tell us more about your requirement? It will help us understand the issue correctly.

**Comment by pauljegouic** [comment]
I would like to be able to create in the same module :

- My CIS instance,
- My CIS domain,
- My domain settings,
- WAF activation.

The latest point is causing me trouble.

**Comment by pauljegouic** [comment]
<img width="717" alt="image" src="https://github.com/IBM-Cloud/terraform-provider-ibm/assets/50360031/133988aa-75c2-42b6-99be-09b6e109ba67">

And because the entrypoint ruleset resource cannot be created, It cannot fit my need.

N.B: the import resource within the module is not acceptable since this _import_ resource (terraform native), is not compatible with variabilization of the ID, and I don't want to have to deploy twice my module to be fully functional like :

- Deploy #1
    - Create instance,
    - Create domain,
    - Output the ruleset ID,
- Deploy #2
    - inform the rulesetID,
    - do the import,
    - activate WAF rules
    
    
That's not acceptable from my automation prospective

**Comment by arjunchauhanibm** [comment]
To achieve this automation in a same module we have two things in the 4th step - `WAF activation`.   

1. We need to get the ruleset id’s of the waf managed rules that we have to activate/deploy. If you already have a way to get the managed ruleset id's  which you want to activate/deploy, then you can skip this step.  Otherwise we can use the data source `ibm_cis_rulesets` to get the list of managed rulesets that are available and can be deployed. 
More information is present at [ibm_cis_rulesets](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/cis_rulesets). 

Example : 

```
data "ibm_cis_rulesets" "tests" {
    cis_id    = ibm_cis.instance.id
    domain_id = data.ibm_cis_domain.cis_domain.domain_id
}
```


2. To deploy/activate these managed rulesets we use entrypoint ruleset resource - `ibm_cis_ruleset_entrypoint_version`. We still cannot specifically create an endpoint ruleset. But it doesn’t matter when we have to deploy the ruleset for the phase - `http_request_firewall_managed`. So the above api will deploy the ruleset by creating a rule with action as `execute` and it will use the entrypoint ruleset if it already exists. If it does not exist, it will create one. 

More information is present at - [ibm_cis_ruleset_entrypoint_version](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/cis_ruleset_entrypoint_version).

To deploy/activate the rulesets you can use the below example.

```
resource "ibm_cis_ruleset_entrypoint_version" "config" {
    cis_id    = ibm_cis.instance.id
    domain_id = data.ibm_cis_domain.cis_domain.domain_id
    phase = "http_request_firewall_managed"
    rulesets {
      description = "Entry Point ruleset"
      rules {
        action =  "execute"
        action_parameters  {
          id = <id of the ruleset-1 to be deployed>
        }
        description = "deploying ruleset 1"
        enabled = true
        expression = "true"
      }
      rules {
        action =  "execute"
        action_parameters  {
          id = <id of the ruleset-2 to be deployed>
        }
        description = "deploying ruleset 2"
        expression = "true"
        enabled = true
      }
    }
  }
```

**Comment by pauljegouic** [comment]
Will give it a try, thanks a lot for the detailed answer !

**Comment by pauljegouic** [comment]
@arjunchauhanibm 

Thanks a lot for your help. 

<img width="1477" alt="image" src="https://github.com/user-attachments/assets/85daa42b-4250-4337-903e-ab6092987a58">

Closing this issue.
