### ISSUE TITLE
[EN] Error is seen during EN KMS & COS integration when private endpoint is set in CBR rule context for schematics.

### ISSUE THREAD

**Issue by Ak-sky** [IBM-Cloud/terraform-provider-ibm#5525]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

Terraform Version v1.6
Terraform IBM Provider Version v1.67.1

### Affected Resource(s)

* ibm_en_integration
* ibm_en_integration_cos

### Terraform Configuration Files

This EN [FScloud](https://github.com/terraform-ibm-modules/terraform-ibm-event-notifications/tree/main/examples/fscloud) example is failing during integration. Setting up the visibility as [ private in provider](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/guides/custom-service-endpoints#getting-started-with-custom-service-endpoints) is also not working.

>  2024/07/23 13:17:16 Terraform apply |     "Result": {
>  2024/07/23 13:17:16 Terraform apply |         "errors": [
>  2024/07/23 13:17:16 Terraform apply |             {
>  2024/07/23 13:17:16 Terraform apply |                 "code": "authorization_error",
>  2024/07/23 13:17:16 Terraform apply |                 "message": "Unfortunately you don't have a permission to access requested resource",
>  2024/07/23 13:17:16 Terraform apply |                 "more_info": "https://cloud.ibm.com/apidocs/event-notifications#event-notifications-api-authentication"
>  2024/07/23 13:17:16 Terraform apply |             }
>  2024/07/23 13:17:16 Terraform apply |         ],
>  2024/07/23 13:17:16 Terraform apply |         "status_code": 403,
>  2024/07/23 13:17:16 Terraform apply |         "trace": "5f79a128-b1ea-4cb6-8a9d-ef76e9d7b53c"
>  2024/07/23 13:17:16 Terraform apply |     },
>  2024/07/23 13:17:16 Terraform apply |     "RawResult": null
> 
CBR rules 
<img width="304" alt="image" src="https://github.com/user-attachments/assets/67f77bf2-6a26-4e03-9ac5-15deaa79b262">

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please share a link to the ZIP file.
```

### Expected Behavior

KMS & COS integrations should have worked without any issues.

### Actual Behavior

KMS & COS integrations are failing

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by Divya-Singh1693** [comment]
@Ak-sky 

I have tried following scenarios for testing. I have setup CBR for testing for control plane API's

<img width="276" alt="Screenshot 2024-07-25 at 1 04 46 PM" src="https://github.com/user-attachments/assets/e94c76e8-c884-44a7-a892-4fa6a74565cb">

My applied plan went successful

` 2024/07/25 07:29:57 [1m-----  New Workspace Action  -----[21m[0m
 2024/07/25 07:29:57 Request: activitId=f3684ad7d46aac497fd5b7fb7af79bc2, account=97e9a474ce304c06a7ca0117ce618cd4, owner=Divya.Singh1@ibm.com, requestID=16bfe140-69a4-4bd6-8613-3407a0483ec1
 2024/07/25 07:29:58 Related Activity: action=APPLY, workspaceID=us-east.workspace.tf-test.6aad4c5d, processedBy=orchestrator-6557f45f9d-tjcbz
 2024/07/25 07:29:58 Related Workspace: name=tf-test, sourcerelease=(not specified), sourceurl=https://github.ibm.com/Divya-Singh1/CSAR_TEST.git, folder=Terraform-Test
 2024/07/25 07:30:01  --- Ready to execute the command --- 
 2024/07/25 07:30:13 workspace.template.StateFile: d106646e-19ff-4d43-9976-272f836b91e4
 2024/07/25 07:30:15 workspace.template.SecFile: 5672db79-a768-417b-b96c-4f1fbedc624d
 2024/07/25 07:30:02 [1m-----  New Action  -----[21m[0m
 2024/07/25 07:30:02 Request: requestID=16bfe140-69a4-4bd6-8613-3407a0483ec1
 2024/07/25 07:30:19 Related Activity: action=Apply, workspaceID=us-east.workspace.tf-test.6aad4c5d, processedByOrchestrator=16bfe140-69a4-4bd6-8613-3407a0483ec1_f3684ad7d46aac497fd5b7fb7af79bc2, processedByJob=job12-6b649bcdb8-bgzss, actionType=Terraform
 
 2024/07/25 07:30:24 [1m-----  Terraform INIT  -----[21m[0m
 
 2024/07/25 07:30:24 [34mStarting command: terraform1.6 init -input=false -no-color[39m[0m
 2024/07/25 07:30:24 Starting command: terraform1.6 init -input=false -no-color
 2024/07/25 07:30:24 Terraform init | 
 2024/07/25 07:30:24 Terraform init | Initializing the backend...
 2024/07/25 07:30:24 Terraform init | 
 2024/07/25 07:30:24 Terraform init | Initializing provider plugins...
 2024/07/25 07:30:24 Terraform init | - Finding ibm-cloud/ibm versions matching "1.67.1"...
 2024/07/25 07:30:25 Terraform init | - Installing ibm-cloud/ibm v1.67.1...
 2024/07/25 07:30:33 Terraform init | - Installed ibm-cloud/ibm v1.67.1 (self-signed, key ID AAD3B791C49CC253)
 2024/07/25 07:30:33 Terraform init | 
 2024/07/25 07:30:33 Terraform init | Partner and community providers are signed by their developers.
 2024/07/25 07:30:33 Terraform init | If you'd like to know more about provider signing, you can read about it here:
 2024/07/25 07:30:33 Terraform init | https://www.terraform.io/docs/cli/plugins/signing.html
 2024/07/25 07:30:33 Terraform init | 
 2024/07/25 07:30:33 Terraform init | Terraform has created a lock file .terraform.lock.hcl to record the provider
 2024/07/25 07:30:33 Terraform init | selections it made above. Include this file in your version control repository
 2024/07/25 07:30:33 Terraform init | so that Terraform can guarantee to make the same selections by default when
 2024/07/25 07:30:33 Terraform init | you run "terraform init" in the future.
 2024/07/25 07:30:33 Terraform init | 
 2024/07/25 07:30:33 Terraform init | Terraform has been successfully initialized!
 2024/07/25 07:30:33 Command finished successfully.
 
 2024/07/25 07:30:33 [1m-----  Terraform APPLY  -----[21m[0m
 
 2024/07/25 07:30:33 [34mStarting command: terraform1.6 apply -state=terraform.tfstate -var-file=schematics.tfvars -auto-approve -no-color[39m[0m
 2024/07/25 07:30:33 Starting command: terraform1.6 apply -state=terraform.tfstate -var-file=schematics.tfvars -auto-approve -no-color
 2024/07/25 07:30:41 Terraform apply | 
 2024/07/25 07:30:41 Terraform apply | Terraform used the selected providers to generate the following execution
 2024/07/25 07:30:41 Terraform apply | plan. Resource actions are indicated with the following symbols:
 2024/07/25 07:30:41 Terraform apply |   + create
 2024/07/25 07:30:41 Terraform apply |  <= read (data resources)
 2024/07/25 07:30:41 Terraform apply | 
 2024/07/25 07:30:41 Terraform apply | Terraform will perform the following actions:
 2024/07/25 07:30:41 Terraform apply | 
 2024/07/25 07:30:41 Terraform apply |   # data.ibm_en_integration_cos.data_integrationcos will be read during apply
 2024/07/25 07:30:41 Terraform apply |   # (config refers to values not yet known)
 2024/07/25 07:30:41 Terraform apply |  <= data "ibm_en_integration_cos" "data_integrationcos" {
 2024/07/25 07:30:41 Terraform apply |       + id             = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + instance_guid  = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + integration_id = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + metadata       = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + type           = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + updated_at     = (known after apply)
 2024/07/25 07:30:41 Terraform apply |     }
 2024/07/25 07:30:41 Terraform apply | 
 2024/07/25 07:30:41 Terraform apply |   # data.ibm_en_integrations.list_integrations will be read during apply
 2024/07/25 07:30:41 Terraform apply |   # (config refers to values not yet known)
 2024/07/25 07:30:41 Terraform apply |  <= data "ibm_en_integrations" "list_integrations" {
 2024/07/25 07:30:41 Terraform apply |       + id            = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + instance_guid = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + integrations  = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + total_count   = (known after apply)
 2024/07/25 07:30:41 Terraform apply |     }
 2024/07/25 07:30:41 Terraform apply | 
 2024/07/25 07:30:41 Terraform apply |   # ibm_en_destination_ce.codeengine_en_destination_application will be created
 2024/07/25 07:30:41 Terraform apply |   + resource "ibm_en_destination_ce" "codeengine_en_destination_application" {
 2024/07/25 07:30:41 Terraform apply |       + collect_failed_events = false
 2024/07/25 07:30:41 Terraform apply |       + description           = "Code Engine destination for event notification update"
 2024/07/25 07:30:41 Terraform apply |       + destination_id        = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + id                    = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + instance_guid         = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + name                  = "Code engine Destination update"
 2024/07/25 07:30:41 Terraform apply |       + subscription_count    = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + subscription_names    = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + type                  = "ibmce"
 2024/07/25 07:30:41 Terraform apply |       + updated_at            = (known after apply)
 2024/07/25 07:30:41 Terraform apply | 
 2024/07/25 07:30:41 Terraform apply |       + config {
 2024/07/25 07:30:41 Terraform apply |           + params {
 2024/07/25 07:30:41 Terraform apply |               + custom_headers    = {
 2024/07/25 07:30:41 Terraform apply |                   + "authorization" = "authorization"
 2024/07/25 07:30:41 Terraform apply |                 }
 2024/07/25 07:30:41 Terraform apply |               + sensitive_headers = [
 2024/07/25 07:30:41 Terraform apply |                   + "authorization",
 2024/07/25 07:30:41 Terraform apply |                 ]
 2024/07/25 07:30:41 Terraform apply |               + type              = "application"
 2024/07/25 07:30:41 Terraform apply |               + url               = "https://test.codetestcodeengine.com"
 2024/07/25 07:30:41 Terraform apply |               + verb              = "POST"
 2024/07/25 07:30:41 Terraform apply |             }
 2024/07/25 07:30:41 Terraform apply |         }
 2024/07/25 07:30:41 Terraform apply |     }
 2024/07/25 07:30:41 Terraform apply | 
 2024/07/25 07:30:41 Terraform apply |   # ibm_en_integration_cos.integrationcos will be created
 2024/07/25 07:30:41 Terraform apply |   + resource "ibm_en_integration_cos" "integrationcos" {
 2024/07/25 07:30:41 Terraform apply |       + id             = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + instance_guid  = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + integration_id = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + type           = "collect_failed_events"
 2024/07/25 07:30:41 Terraform apply |       + updated_at     = (known after apply)
 2024/07/25 07:30:41 Terraform apply | 
 2024/07/25 07:30:41 Terraform apply |       + metadata {
 2024/07/25 07:30:41 Terraform apply |           + bucket_name = "test-goldeneye-en-integration"
 2024/07/25 07:30:41 Terraform apply |           + crn         = "crn:v1:bluemix:public:cloud-object-storage:global:a/2fd203a53d9025d28559b6ad1a3ba13c:88f2c389-3dbd-4e28-a948-a6f4762d7fd3::"
 2024/07/25 07:30:41 Terraform apply |           + endpoint    = "https://s3.us-south.cloud-object-storage.appdomain.cloud"
 2024/07/25 07:30:41 Terraform apply |         }
 2024/07/25 07:30:41 Terraform apply |     }
 2024/07/25 07:30:41 Terraform apply | 
 2024/07/25 07:30:41 Terraform apply |   # ibm_en_source.en_source will be created
 2024/07/25 07:30:41 Terraform apply |   + resource "ibm_en_source" "en_source" {
 2024/07/25 07:30:41 Terraform apply |       + description   = "API source for Event Notifications destinations"
 2024/07/25 07:30:41 Terraform apply |       + enabled       = true
 2024/07/25 07:30:41 Terraform apply |       + id            = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + instance_guid = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + name          = "EN Source Terraform backend"
 2024/07/25 07:30:41 Terraform apply |       + source_id     = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + updated_at    = (known after apply)
 2024/07/25 07:30:41 Terraform apply |     }
 2024/07/25 07:30:41 Terraform apply | 
 2024/07/25 07:30:41 Terraform apply |   # ibm_iam_authorization_policy.policy will be created
 2024/07/25 07:30:41 Terraform apply |   + resource "ibm_iam_authorization_policy" "policy" {
 2024/07/25 07:30:41 Terraform apply |       + id                          = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + roles                       = [
 2024/07/25 07:30:41 Terraform apply |           + "Reader",
 2024/07/25 07:30:41 Terraform apply |           + "Object Writer",
 2024/07/25 07:30:41 Terraform apply |         ]
 2024/07/25 07:30:41 Terraform apply |       + source_resource_group_id    = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + source_resource_instance_id = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + source_resource_type        = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + source_service_account      = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + source_service_name         = "event-notifications"
 2024/07/25 07:30:41 Terraform apply |       + target_resource_group_id    = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + target_resource_instance_id = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + target_resource_type        = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + target_service_name         = "cloud-object-storage"
 2024/07/25 07:30:41 Terraform apply |       + transaction_id              = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + version                     = (known after apply)
 2024/07/25 07:30:41 Terraform apply |     }
 2024/07/25 07:30:41 Terraform apply | 
 2024/07/25 07:30:41 Terraform apply |   # ibm_resource_instance.Terraform_Integration_Test will be created
 2024/07/25 07:30:41 Terraform apply |   + resource "ibm_resource_instance" "Terraform_Integration_Test" {
 2024/07/25 07:30:41 Terraform apply |       + account_id              = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + allow_cleanup           = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + created_at              = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + created_by              = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + crn                     = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + dashboard_url           = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + deleted_at              = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + deleted_by              = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + extensions              = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + guid                    = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + id                      = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + last_operation          = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + location                = "us-south"
 2024/07/25 07:30:41 Terraform apply |       + locked                  = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + name                    = "Terraform_Integration_Test"
 2024/07/25 07:30:41 Terraform apply |       + plan                    = "lite"
 2024/07/25 07:30:41 Terraform apply |       + plan_history            = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + resource_aliases_url    = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + resource_bindings_url   = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + resource_controller_url = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + resource_crn            = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + resource_group_crn      = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + resource_group_id       = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + resource_group_name     = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + resource_id             = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + resource_keys_url       = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + resource_name           = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + resource_plan_id        = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + resource_status         = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + restored_at             = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + restored_by             = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + scheduled_reclaim_at    = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + scheduled_reclaim_by    = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + service                 = "event-notifications"
 2024/07/25 07:30:41 Terraform apply |       + service_endpoints       = "public-and-private"
 2024/07/25 07:30:41 Terraform apply |       + state                   = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + status                  = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + sub_type                = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + tags                    = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + target_crn              = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + type                    = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + update_at               = (known after apply)
 2024/07/25 07:30:41 Terraform apply |       + update_by               = (known after apply)
 2024/07/25 07:30:41 Terraform apply |     }
 2024/07/25 07:30:41 Terraform apply | 
 2024/07/25 07:30:41 Terraform apply | Plan: 5 to add, 0 to change, 0 to destroy.
 2024/07/25 07:30:42 Terraform apply | ibm_iam_authorization_policy.policy: Creating...
 2024/07/25 07:30:42 Terraform apply | ibm_resource_instance.Terraform_Integration_Test: Creating...
 2024/07/25 07:30:43 Terraform apply | ibm_iam_authorization_policy.policy: Creation complete after 2s [id=043876e9-923f-4991-9f3c-bc07914a5a04]
 2024/07/25 07:30:52 Terraform apply | ibm_resource_instance.Terraform_Integration_Test: Still creating... [10s elapsed]
 2024/07/25 07:31:02 Terraform apply | ibm_resource_instance.Terraform_Integration_Test: Still creating... [20s elapsed]
 2024/07/25 07:31:12 Terraform apply | ibm_resource_instance.Terraform_Integration_Test: Still creating... [30s elapsed]
 2024/07/25 07:31:22 Terraform apply | ibm_resource_instance.Terraform_Integration_Test: Still creating... [40s elapsed]
 2024/07/25 07:31:32 Terraform apply | ibm_resource_instance.Terraform_Integration_Test: Still creating... [50s elapsed]
 2024/07/25 07:31:42 Terraform apply | ibm_resource_instance.Terraform_Integration_Test: Still creating... [1m0s elapsed]
 2024/07/25 07:31:52 Terraform apply | ibm_resource_instance.Terraform_Integration_Test: Still creating... [1m10s elapsed]
 2024/07/25 07:32:02 Terraform apply | ibm_resource_instance.Terraform_Integration_Test: Creation complete after 1m20s [id=crn:v1:bluemix:public:event-notifications:us-south:a/2fd203a53d9025d28559b6ad1a3ba13c:cf0ccaf3-5c62-4798-9838-96a85a3ae122::]
 2024/07/25 07:32:02 Terraform apply | ibm_en_source.en_source: Creating...
 2024/07/25 07:32:02 Terraform apply | ibm_en_integration_cos.integrationcos: Creating...
 2024/07/25 07:32:02 Terraform apply | ibm_en_destination_ce.codeengine_en_destination_application: Creating...
 2024/07/25 07:32:02 Terraform apply | ibm_en_source.en_source: Creation complete after 1s [id=cf0ccaf3-5c62-4798-9838-96a85a3ae122/ead03450-96f9-4947-b48e-26295804ac90:api]
 2024/07/25 07:32:03 Terraform apply | ibm_en_integration_cos.integrationcos: Creation complete after 2s [id=cf0ccaf3-5c62-4798-9838-96a85a3ae122/2e507f09-2e98-4080-99e7-5563b7adc627]
 2024/07/25 07:32:03 Terraform apply | data.ibm_en_integration_cos.data_integrationcos: Reading...
 2024/07/25 07:32:03 Terraform apply | data.ibm_en_integrations.list_integrations: Reading...
 2024/07/25 07:32:03 Terraform apply | data.ibm_en_integration_cos.data_integrationcos: Read complete after 0s [id=cf0ccaf3-5c62-4798-9838-96a85a3ae122/2e507f09-2e98-4080-99e7-5563b7adc627]
 2024/07/25 07:32:03 Terraform apply | ibm_en_destination_ce.codeengine_en_destination_application: Creation complete after 2s [id=cf0ccaf3-5c62-4798-9838-96a85a3ae122/8ee034ad-ec0d-4838-8e89-e4816305bb5f]
 2024/07/25 07:32:03 Terraform apply | data.ibm_en_integrations.list_integrations: Read complete after 0s [id=integrations/cf0ccaf3-5c62-4798-9838-96a85a3ae122]
 2024/07/25 07:32:04 Terraform apply | 
 2024/07/25 07:32:04 Terraform apply | Apply complete! Resources: 5 added, 0 changed, 0 destroyed.
 2024/07/25 07:32:04 Command finished successfully.
 
 2024/07/25 07:32:04 [1m-----  Terraform Refresh  -----[21m[0m
 
 2024/07/25 07:32:04 [34mStarting command: terraform1.6 refresh -state=terraform.tfstate -var-file=schematics.tfvars -no-color[39m[0m
 2024/07/25 07:32:04 Starting command: terraform1.6 refresh -state=terraform.tfstate -var-file=schematics.tfvars -no-color
 2024/07/25 07:32:11 Terraform refresh | ibm_resource_instance.Terraform_Integration_Test: Refreshing state... [id=crn:v1:bluemix:public:event-notifications:us-south:a/2fd203a53d9025d28559b6ad1a3ba13c:cf0ccaf3-5c62-4798-9838-96a85a3ae122::]
 2024/07/25 07:32:11 Terraform refresh | ibm_iam_authorization_policy.policy: Refreshing state... [id=043876e9-923f-4991-9f3c-bc07914a5a04]
 2024/07/25 07:32:13 Terraform refresh | ibm_en_integration_cos.integrationcos: Refreshing state... [id=cf0ccaf3-5c62-4798-9838-96a85a3ae122/2e507f09-2e98-4080-99e7-5563b7adc627]
 2024/07/25 07:32:13 Terraform refresh | ibm_en_source.en_source: Refreshing state... [id=cf0ccaf3-5c62-4798-9838-96a85a3ae122/ead03450-96f9-4947-b48e-26295804ac90:api]
 2024/07/25 07:32:13 Terraform refresh | ibm_en_destination_ce.codeengine_en_destination_application: Refreshing state... [id=cf0ccaf3-5c62-4798-9838-96a85a3ae122/8ee034ad-ec0d-4838-8e89-e4816305bb5f]
 2024/07/25 07:32:13 Terraform refresh | data.ibm_en_integrations.list_integrations: Reading...
 2024/07/25 07:32:13 Terraform refresh | data.ibm_en_integration_cos.data_integrationcos: Reading...
 2024/07/25 07:32:13 Terraform refresh | data.ibm_en_integration_cos.data_integrationcos: Read complete after 0s [id=cf0ccaf3-5c62-4798-9838-96a85a3ae122/2e507f09-2e98-4080-99e7-5563b7adc627]
 2024/07/25 07:32:13 Terraform refresh | data.ibm_en_integrations.list_integrations: Read complete after 0s [id=integrations/cf0ccaf3-5c62-4798-9838-96a85a3ae122]
 2024/07/25 07:32:13 Command finished successfully.
 
 2024/07/25 07:32:13 [1m-----  Terraform OUTPUT  -----[21m[0m
 
 2024/07/25 07:32:13 [34mStarting command: terraform1.6 output -no-color -json[39m[0m
 2024/07/25 07:32:13 Starting command: terraform1.6 output -no-color -json
 2024/07/25 07:32:15 Command finished successfully.
 2024/07/25 07:32:22 [1m[32mDone with the workspace action[39m[0m`

**Comment by Divya-Singh1693** [comment]
@Ak-sky We are working on the fix, and it has already been identified and in development.

**Comment by Divya-Singh1693** [comment]
@Ak-sky We have deployed the fix in production. Please check on your end and confirm.

**Comment by Ak-sky** [comment]
This is working fine, closing this.
