### ISSUE TITLE
ibm_is_instance adding a data volume there is no option to auto-delete

### ISSUE THREAD

**Issue by dprosper** [IBM-Cloud/terraform-provider-ibm#646]
### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_is_instance
- ibm_is_volume

### Expected Behavior
The documentation does not indicate how to set the added volumes to automatically delete upon instance deletion.
![image](https://user-images.githubusercontent.com/11874942/61050538-3aa7e300-a3b5-11e9-9ee1-282110689efe.png)

**Comment by js-max** [comment]
Bump on this issue

https://cloud.ibm.com/docs/vpc?topic=vpc-attaching-block-storage-cli

If CLI allows to do that believe that Terraform provider should also allow

**Comment by ErikEvenson** [comment]
Bump.  Somewhat critical for our work.

**Comment by hkantare** [comment]
@ErikEvenson We have not added support to auto-delete volume when instance is destroyed beacuse it makes difficult to maintain the state of volumes...
Let's take a scenario if user provision volume and instance using automation tempalte...If we include an attribute auto-delete the volumes will be destroyed along with instance but when volume resource start to destroy it will fail because already volume is deleted by instance..

Unlike IBM Cloud Cli terraform needs to maintain the state of each resource/datasource for its smooth execution. If one resource controls the behaviour of other resource then we will not have consistent or valid state information.

**Comment by dprosper** [comment]
@hkantare you are then assuming that the instance will be deleted eventually via Terraform.  I think the ability to add the auto-delete should still be available, default to false and the documentation can offer up your reasoning above for not setting it to true and let the engineer decide to use it or not.

**Comment by kavya498** [comment]
Available in [1.21.0](https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.21.0)
