### ISSUE TITLE
Do not recreate resource on service endpoint update.

### ISSUE THREAD

**Issue by grommir** [IBM-Cloud/terraform-provider-ibm#719]
### Terraform Version
Terraform v0.11.14
+ provider.ibm v0.18.0

### Affected Resource(s)
- ibm_resource_instance

### Terraform Configuration Files
Created next resource
```hcl
resource "ibm_resource_instance" "postgresql" {
    name = "${var.name}"
    service = "databases-for-postgresql"
    plan = "standard"
    location = "${var.region}"
    resource_group_id = "${data.ibm_resource_group.group.id}"
}
```
After creation - update resource with new service endpoint
```hcl
resource "ibm_resource_instance" "postgresql" {
    name = "${var.name}"
    service = "databases-for-postgresql"
    plan = "standard"
    location = "${var.region}"
    resource_group_id = "${data.ibm_resource_group.group.id}"

    parameters = {
      "service-endpoints" = "private"
    }

}
```

### Expected Behavior
Existing database updated.

### Actual Behavior
Database recreated.

**Comment by hkantare** [comment]
Yes..When we have any changes in properties we are destroying and recreating the instance because the GET API https://cloud.ibm.com/apidocs/resource-controller#get-a-resource-instance is not returning the properties which we used why creating if API doesn't return back we cannot store them in terraform state file to see if we have any diff while creating and updating.

**Comment by hkantare** [comment]
Supported service-endpoints has attribute for resource_instance. 
https://ibm-cloud.github.io/tf-ibm-docs/v0.19.1/r/resource_instance.html
Please use ibm_database resource to provision database services
https://ibm-cloud.github.io/tf-ibm-docs/v0.19.1/r/database.html
