### ISSUE TITLE
Feature Request: Support NLB configuration

### ISSUE THREAD

**Issue by somaya10** [IBM-Cloud/terraform-provider-ibm#730]
Provide a native mechanism to configure NLBs

### Terraform Version
0.11.x

### Affected Resource(s)
n/a

**Comment by somaya10** [comment]
https://cloud.ibm.com/docs/containers?topic=containers-loadbalancer#loadbalancer

**Comment by jfeddern** [comment]
I would like to use such a feature as well.

**Comment by Hertog-PJ** [comment]
We would also appreciate this feature.

**Comment by kavya498** [comment]
https://cloud.ibm.com/docs/containers?topic=containers-loadbalancer#loadbalancer
This link uses all kubernetes APIs and hence this has to be configured via Kubernetes provider

Using IBM Provider, you can configure using [container_nlb_dns](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/container_nlb_dns) resource. 
This feature is available from [1.37.0 release](https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.37.0)

Since this is very old issue.. I ll be closing this issue.. 
Kindly open a new issue and tag this issue, if you feel that the `container_nlb_dns` doesn't meet for your requirement..

Thanks.
