### ISSUE TITLE
ibm_is_public_gateway has incorrect documentation

### ISSUE THREAD

**Issue by CosmicQ** [IBM-Cloud/terraform-provider-ibm#860]
The documentation for `ibm_is_public_gateway` lists `floating_ip` as an argument, but it really is an attribute (not listed).

**Comment by CosmicQ** [comment]
The only way I get this to work is like this:

```
resource "ibm_is_public_gateway" "gate" {
  count           = "${length(var.public_subnets)}"
  name            = "${var.name}-gate-${count.index +1}"
  zone            = "${var.zones[count.index]}"
  vpc             = "${ibm_is_vpc.vpc.id}"
  floating_ip     = {
    id      = ""
    address = ""
  }
}

output "gateway_ips" {
  description = "List of gateway IP addresses"
  value       = ["${ibm_is_public_gateway.gate.*.floating_ip.address}"]
}
```

I have to define `floating_ip` in order to retrieve the floating IP from the gateway.

**Comment by VaishnaviGopal** [comment]
In order to access the floating_ip address use this syntax : 
value       = ["${ibm_is_public_gateway.gate.floating_ip["address"]}"]

**The updated tf file is looked like this:**


resource "ibm_is_public_gateway" "gate" {
  count           = "${length(var.public_subnets)}"
  name            = "${var.name}-gate-${count.index +1}"
  zone            = "${var.zones[count.index]}"
  vpc             = "${ibm_is_vpc.vpc.id}"

output "gateway_ips" {
  description = "List of gateway IP addresses"
  value       = ["${ibm_is_public_gateway.gate.floating_ip["address"]}"]
